const MAX_TEXT_LENGTH = 12000;
const MAX_URL_HTML_LENGTH = 160000;

function json(res, status, body) {
  res.statusCode = status;
  res.setHeader('Content-Type', 'application/json; charset=utf-8');
  res.setHeader('Cache-Control', 'no-store');
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  res.end(JSON.stringify(body));
}

function normalizeBody(req) {
  return new Promise((resolve, reject) => {
    let data = '';
    req.on('data', (chunk) => {
      data += chunk;
      if (data.length > 1_500_000) {
        reject(new Error('Request too large'));
        req.destroy();
      }
    });
    req.on('end', () => {
      try {
        resolve(data ? JSON.parse(data) : {});
      } catch {
        reject(new Error('Invalid JSON'));
      }
    });
    req.on('error', reject);
  });
}

function clampScore(score) {
  return Math.max(8, Math.min(96, Math.round(score)));
}

function statusFromScore(score) {
  if (score >= 82) return { label: 'High concern', tone: 'concern' };
  if (score >= 58) return { label: 'Use care', tone: 'care' };
  return { label: 'Likely okay', tone: 'ok' };
}

function evidence(label, weight, detail) {
  return { label, weight, detail };
}

function lower(value) {
  return String(value || '').toLowerCase();
}

function detectUrgency(text) {
  return /(share|forward|send).{0,20}(now|fast|before|urgent)|urgent|breaking|they don't want you to know|before it disappears|limited time|act now/i.test(text);
}

function detectSourceLanguage(text) {
  return /(according to|reported by|source:|via |published|study|court|agency|official|press release|archive)/i.test(text);
}

function summarizeSignals(signals) {
  if (!signals.length) {
    return 'We did not find strong warning signs in this quick scan. Still check the source before sharing.';
  }
  const top = signals.slice(0, 2).map((item) => item.label.toLowerCase()).join(' and ');
  return `We noticed ${top}. That does not prove AI involvement, but it is worth checking before sharing.`;
}

async function fetchUrlSignals(url) {
  const signals = [];
  const metadata = {};
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 4500);

  try {
    const response = await fetch(url, {
      redirect: 'follow',
      signal: controller.signal,
      headers: {
        'User-Agent': 'clAIrity-preview-scanner/1.0'
      }
    });
    metadata.httpStatus = response.status;
    metadata.finalUrl = response.url;
    metadata.contentType = response.headers.get('content-type') || 'unknown';

    if (!response.ok) {
      signals.push(evidence('Page could not be read clearly', 'Medium', `The page returned HTTP ${response.status}.`));
      return { signals, metadata, text: '' };
    }

    const contentType = metadata.contentType;
    if (!contentType.includes('text/html') && !contentType.includes('text/plain')) {
      signals.push(evidence('Link is not a normal readable page', 'Medium', `The response type was ${contentType}.`));
      return { signals, metadata, text: '' };
    }

    const html = (await response.text()).slice(0, MAX_URL_HTML_LENGTH);
    const title = html.match(/<title[^>]*>([^<]+)<\/title>/i)?.[1]?.trim();
    const description = html.match(/<meta[^>]+name=["']description["'][^>]+content=["']([^"']+)/i)?.[1]?.trim()
      || html.match(/<meta[^>]+property=["']og:description["'][^>]+content=["']([^"']+)/i)?.[1]?.trim();
    const imageCount = (html.match(/<img\b/gi) || []).length;
    const videoCount = (html.match(/<video\b|og:video|twitter:player/gi) || []).length;
    const published = /article:published_time|datePublished|published|datetime=/i.test(html);
    const author = /author|article:author|byline/i.test(html);
    const aiTerms = /ai-generated|synthetic media|deepfake|made with ai|generated by ai|watermark/i.test(html);
    const repostTerms = /repost|viral|shared from|originally posted|via @|credit:/i.test(html);

    metadata.title = title || '';
    metadata.description = description || '';
    metadata.imageCount = imageCount;
    metadata.videoCount = videoCount;

    if (!published) signals.push(evidence('No clear publication date found', 'Medium', 'The page did not expose an obvious date signal.'));
    if (!author) signals.push(evidence('No clear author or source found', 'Medium', 'The page did not expose an obvious author/source signal.'));
    if (aiTerms) signals.push(evidence('AI or synthetic-media language appears on the page', 'High', 'The page text mentions AI generation or synthetic media.'));
    if (repostTerms) signals.push(evidence('Repost or credit language appears', 'Medium', 'The page may be showing a copy rather than the original source.'));
    if (imageCount > 8) signals.push(evidence('Many images appear on the page', 'Low', 'A media-heavy page can make source context harder to verify.'));

    return { signals, metadata, text: [title, description].filter(Boolean).join(' ') };
  } catch (error) {
    signals.push(evidence('Page scan could not finish', 'Medium', 'The page may block automated reading or took too long to respond.'));
    metadata.error = error.name === 'AbortError' ? 'Timed out while reading page' : error.message;
    return { signals, metadata, text: '' };
  } finally {
    clearTimeout(timeout);
  }
}

async function analyzeUrl(payload) {
  const input = String(payload.content || payload.url || '').trim();
  let score = 38;
  const signals = [];
  const limitations = ['Webpage scans can miss content that appears only after login, paywalls, or heavy scripts.'];

  let parsed;
  try {
    parsed = new URL(input);
  } catch {
    return buildResult({
      type: 'url',
      label: 'Invalid web link',
      score: 70,
      signals: [evidence('The link could not be read', 'High', 'Enter a full URL such as https://example.com/story.')],
      nextStep: 'Paste a full webpage or social post link and scan again.',
      limitations
    });
  }

  const host = lower(parsed.hostname);
  if (/example|localhost|test/.test(host)) signals.push(evidence('Sample or local domain', 'Low', 'This looks like a prototype/test link, so source checks are limited.'));
  if (/x\.com|twitter|tiktok|instagram|facebook|threads|reddit|youtube|social/.test(host)) {
    score += 12;
    signals.push(evidence('Social platform context', 'Medium', 'Social posts are often reposted without the original source attached.'));
  }
  if (parsed.protocol !== 'https:') {
    score += 9;
    signals.push(evidence('Link is not HTTPS', 'Medium', 'Non-HTTPS pages provide weaker source and integrity signals.'));
  }

  const fetched = await fetchUrlSignals(parsed.href);
  signals.push(...fetched.signals);
  score += fetched.signals.reduce((total, item) => total + weightValue(item.weight), 0);

  const textSignals = analyzeTextSignals(fetched.text || parsed.href);
  signals.push(...textSignals.signals.slice(0, 2));
  score += textSignals.scoreDelta;

  return buildResult({
    type: 'url',
    label: fetched.metadata.title || parsed.hostname,
    score,
    signals,
    nextStep: 'Look for the original source, author, and date before sharing this link.',
    metadata: fetched.metadata,
    limitations
  });
}

function weightValue(weight) {
  if (weight === 'High') return 17;
  if (weight === 'Medium') return 10;
  return 4;
}

function analyzeTextSignals(text) {
  const safeText = String(text || '').slice(0, MAX_TEXT_LENGTH);
  const signals = [];
  let scoreDelta = 0;
  const words = safeText.trim().split(/\s+/).filter(Boolean);

  if (detectUrgency(safeText)) {
    scoreDelta += 15;
    signals.push(evidence('Urgent sharing language', 'High', 'The wording pushes people to share quickly before checking the source.'));
  }
  if (!detectSourceLanguage(safeText)) {
    scoreDelta += 12;
    signals.push(evidence('No named source in the text', 'High', 'The text does not clearly say where the claim came from.'));
  }
  if (/[!?]{2,}|ALL CAPS|MUST SEE|SHOCKING/i.test(safeText)) {
    scoreDelta += 8;
    signals.push(evidence('High-emotion formatting', 'Medium', 'The text uses formatting that can pressure people to react quickly.'));
  }
  if (words.length < 8) {
    scoreDelta += 4;
    signals.push(evidence('Very little text to check', 'Low', 'A short sample gives clAIrity fewer context clues.'));
  }
  if (/(as an ai|language model|chatgpt|generated)/i.test(safeText)) {
    scoreDelta += 18;
    signals.push(evidence('AI-related wording appears', 'High', 'The text includes language associated with generated or AI-assisted writing.'));
  }
  if (detectSourceLanguage(safeText) && !detectUrgency(safeText)) {
    scoreDelta -= 10;
    signals.push(evidence('Source language appears', 'Low', 'The text includes words that point to a source or publication context.'));
  }

  return { scoreDelta, signals };
}

function analyzeText(payload) {
  const content = String(payload.content || '').slice(0, MAX_TEXT_LENGTH);
  const analysis = analyzeTextSignals(content);
  let score = 34 + analysis.scoreDelta;

  return buildResult({
    type: 'text',
    label: content.slice(0, 42) || 'Text scan',
    score,
    signals: analysis.signals,
    nextStep: 'Search for a dated source from a trusted outlet before sharing the claim.',
    metadata: { length: content.length, words: content.trim().split(/\s+/).filter(Boolean).length },
    limitations: ['Text scans check wording and source clues. They do not verify every factual claim.']
  });
}

function analyzeMedia(payload) {
  const media = payload.media || {};
  const mediaType = lower(payload.type || media.type || 'image').includes('audio')
    ? 'audio'
    : lower(payload.type || media.type || 'image').includes('video')
      ? 'video'
      : 'image';
  const signals = [];
  let score = mediaType === 'audio' ? 45 : mediaType === 'video' ? 42 : 40;

  if (!media.name) {
    signals.push(evidence('No filename context', 'Low', 'The file did not include a useful name to compare with the content.'));
    score += 4;
  }
  if (media.size && media.size < 30_000) {
    signals.push(evidence('Very small file', 'Medium', 'Tiny media files can hide quality clues or be heavily compressed.'));
    score += 10;
  }
  if (media.size && media.size > 40_000_000) {
    signals.push(evidence('Large media file', 'Low', 'Large media may need a slower full scan for deeper frame/audio analysis.'));
    score += 3;
  }
  if (media.width && media.height) {
    const ratio = media.width / media.height;
    if (ratio > 2.4 || ratio < 0.38) {
      signals.push(evidence('Unusual aspect ratio', 'Low', 'The dimensions are unusual and may come from a crop or generated layout.'));
      score += 5;
    } else {
      signals.push(evidence('Readable dimensions found', 'Low', `The file reports ${media.width} x ${media.height}px dimensions.`));
      score -= 5;
    }
  }
  if (media.lastModifiedAgeDays != null && media.lastModifiedAgeDays < 1) {
    signals.push(evidence('Recently changed file', 'Medium', 'The file metadata says it was modified recently.'));
    score += 8;
  }
  if (/ai|generated|synthetic|deepfake|edited|final-v\d/i.test(media.name || '')) {
    signals.push(evidence('Filename suggests generated or edited media', 'High', 'The filename includes terms such as AI, generated, synthetic, or edited.'));
    score += 18;
  }
  if (mediaType === 'audio') {
    signals.push(evidence('Audio requires voice confirmation', 'Medium', 'This MVP checks metadata only. Confirm sensitive voice messages through another channel.'));
    score += 8;
  }
  if (mediaType === 'video') {
    signals.push(evidence('Video needs frame-level follow-up', 'Medium', 'This MVP checks file metadata only. A deeper scan would sample frames and audio.'));
    score += 7;
  }

  return buildResult({
    type: mediaType,
    label: media.name || `${mediaType} upload`,
    score,
    signals,
    nextStep: mediaType === 'audio'
      ? 'Confirm the message with the person through another channel.'
      : 'Look for the original post or source before sharing this media.',
    metadata: media,
    limitations: ['Upload scans in this MVP use browser-provided metadata only; raw files are not stored server-side.']
  });
}

function buildResult({ type, label, score, signals, nextStep, metadata = {}, limitations = [] }) {
  const normalizedSignals = signals.length
    ? signals
    : [evidence('No strong warning signs found', 'Low', 'The quick scan did not find strong concern signals.')];
  const finalScore = clampScore(score);
  const status = statusFromScore(finalScore);

  return {
    id: `scan_${Date.now()}_${Math.random().toString(16).slice(2)}`,
    createdAt: new Date().toISOString(),
    type,
    label,
    score: finalScore,
    status: status.label,
    tone: status.tone,
    summary: summarizeSignals(normalizedSignals),
    evidence: normalizedSignals.slice(0, 6),
    nextStep,
    metadata,
    limitations,
    privacy: {
      storedServerSide: false,
      rawInputRetained: false
    }
  };
}

module.exports = async function handler(req, res) {
  if (req.method === 'OPTIONS') return json(res, 204, {});
  if (req.method !== 'POST') return json(res, 405, { error: 'Use POST /api/scan' });

  try {
    const payload = await normalizeBody(req);
    const type = lower(payload.type || payload.sourceKind || 'text');
    let result;

    if (type === 'url' || type === 'link' || payload.url) {
      result = await analyzeUrl(payload);
    } else if (type === 'image' || type === 'video' || type === 'audio' || payload.media) {
      result = analyzeMedia(payload);
    } else {
      result = analyzeText(payload);
    }

    return json(res, 200, { result });
  } catch (error) {
    return json(res, error.message === 'Request too large' ? 413 : 400, {
      error: error.message || 'Scan failed'
    });
  }
};
